name: Readme
on:
  - push
jobs:
  container-test-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Readme
        id: package
        uses: juliangruber/read-file-action@v1
        with:
            path: ./README.md
      - name: output the message on actions result
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: steps.package.outputs

          

          
 